### ISSUE TITLE
Emulator just displays a black screen

### ISSUE THREAD

**Issue by olalonde** [LedgerHQ/speculos#313]
<img width="889" alt="Screen Shot 2022-07-16 at 3 39 27 PM" src="https://user-images.githubusercontent.com/416585/179356801-ef358ee4-57d6-4545-b3dd-cf5c42c8f570.png">

I tested with 2 apps, https://github.com/LedgerHQ/app-boilerplate and  https://github.com/LedgerHQ/app-recovery-check . I'm running speculos in docker on mac m1. There are no error messages anywhere (consoler or web app).

I tried building the speculos image both with `FROM ghcr.io/ledgerhq/speculos-builder-aarch64:latest AS builder` and 
`FROM ghcr.io/ledgerhq/speculos-builder:latest AS builder` but still same problem.

I use following docker-compose.yml for boilerplate app:

```yaml
version: "3.7"

services:
  make:
    image: ledgerhq/ledger-app-builder
    volumes:
      - .:/app
    working_dir: "/app"
    command: "make"
  speculos:
    image: speculos
    volumes:
      - ./bin:/apps
    ports:
      - "1234:1234" # gdb
      - "5001:5000" # api
      - "40000:40000" # apdu
      - "41000:41000" # vnc
    stdin_open: true 
    tty: true
    command: "--model nanos /apps/app.elf --sdk 2.0 --seed secret --display text --apdu-port 40000"

```

And start speculos with `docker-compose up speculos`.
